# Font & Spacing
font_family      CaskaydiaCove Nerd Font Mono
font_size        12.0
window_padding_width 12

# Background & Opacity
background_opacity 0.95

allow_remote_control yes
listen_on unix:/tmp/kitty
include ./theme.conf
