preload = /home/twan/.config/hypr/assets/rose-pine-moon-wallpaper.jpeg
splash = false

wallpaper {
    monitor = DP-1
    path = /home/twan/.config/hypr/assets/rose-pine-moon-wallpaper.jpeg
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = /home/twan/.config/hypr/assets/rose-pine-moon-wallpaper.jpeg
    fit_mode = cover
}

